services:
    uam_postmark.swift_transport.postmark:
        class: UAM\Bundle\PostmarkSwiftMailerBundle\SwiftMailer\PostmarkTransport
        arguments:
            - @postmark.message
            - @swiftmailer.transport.eventdispatcher